# Generated by Django 6.0.2 on 2026-03-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
